# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hgiesel/Developer/repos/closet/anki/designer/model_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(303, 154)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.openingTag = QtWidgets.QLineEdit(Settings)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.openingTag.setFont(font)
        self.openingTag.setObjectName("openingTag")
        self.gridLayout.addWidget(self.openingTag, 0, 2, 1, 2)
        self.saveButton = QtWidgets.QPushButton(Settings)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 5, 2, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(Settings)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 5, 3, 1, 1)
        self.closingTag = QtWidgets.QLineEdit(Settings)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.closingTag.setFont(font)
        self.closingTag.setObjectName("closingTag")
        self.gridLayout.addWidget(self.closingTag, 1, 2, 1, 2)
        self.openingLabel = QtWidgets.QLabel(Settings)
        self.openingLabel.setObjectName("openingLabel")
        self.gridLayout.addWidget(self.openingLabel, 0, 0, 1, 2)
        self.line = QtWidgets.QFrame(Settings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 0, 1, 4)
        self.argumentSeparator = QtWidgets.QLineEdit(Settings)
        font = QtGui.QFont()
        font.setFamily("Menlo")
        self.argumentSeparator.setFont(font)
        self.argumentSeparator.setObjectName("argumentSeparator")
        self.gridLayout.addWidget(self.argumentSeparator, 2, 2, 1, 2)
        self.closingLabel = QtWidgets.QLabel(Settings)
        self.closingLabel.setObjectName("closingLabel")
        self.gridLayout.addWidget(self.closingLabel, 1, 0, 1, 2)
        self.separatorLabel = QtWidgets.QLabel(Settings)
        self.separatorLabel.setObjectName("separatorLabel")
        self.gridLayout.addWidget(self.separatorLabel, 2, 0, 1, 2)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Closet Per Model Settings"))
        self.openingTag.setText(_translate("Settings", "[["))
        self.saveButton.setText(_translate("Settings", "Save"))
        self.cancelButton.setText(_translate("Settings", "Cancel"))
        self.closingTag.setText(_translate("Settings", "]]"))
        self.openingLabel.setText(_translate("Settings", "Opening Tag"))
        self.argumentSeparator.setText(_translate("Settings", "::"))
        self.closingLabel.setText(_translate("Settings", "Closing Tag"))
        self.separatorLabel.setText(_translate("Settings", "Argument Separator"))
