# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hgiesel/Developer/repos/closet/anki/designer/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(452, 124)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(Settings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(Settings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 2)
        self.occludeLabel = QtWidgets.QLabel(Settings)
        self.occludeLabel.setObjectName("occludeLabel")
        self.gridLayout.addWidget(self.occludeLabel, 0, 0, 1, 1)
        self.occludeShortcut = QtWidgets.QKeySequenceEdit(Settings)
        self.occludeShortcut.setObjectName("occludeShortcut")
        self.gridLayout.addWidget(self.occludeShortcut, 0, 1, 1, 1)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Closet For Anki Settings"))
        self.label.setText(_translate("Settings", "<html><head/><body><p>Occlusion icon is the <a href=\"https://icons8.com/icons/set/picture-in-picture\"><span style=\" text-decoration: underline; color:#419cff;\">Picture in Picture icon</span></a> by <a href=\"https://icons8.com\"><span style=\" text-decoration: underline; color:#419cff;\">Icons8</span></a></p></body></html>"))
        self.occludeLabel.setToolTip(_translate("Settings", "<html><head/><body><p><br/></p></body></html>"))
        self.occludeLabel.setText(_translate("Settings", "Shortcut for occlusion mode"))
        self.occludeShortcut.setToolTip(_translate("Settings", "<html><head/><body><p>(default: &quot;Ctrl+O&quot;)</p></body></html>"))
